export const FETCH_CART_ITEMS= 'FETCH_CART_ITEMS';
export const CLEAR_CART_ITEMS= 'CLEAR_CART_ITEMS';
export const REMOVE_CART_ITEM= 'REMOVE_CART_ITEM';
export const UPDATE_CART_ITEM_QUANTITY= 'UPDATE_CART_ITEM_QUANTITY';
export const ADD_TO_CART= 'ADD_TO_CART';
// export const INCREASE_QUANTITY= ' INCREASE_QUANTITY';
// export const DECREASE_QUANTITY= ' DECREASE_QUANTITY';